spring.application.name=TSIS

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/tsis_db
spring.datasource.username=tsis_owner
spring.datasource.password=owner1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# create-drop recreates tables at startup (dev only)
# update updates schema without dropping data
# validate only validates schema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.preferred_boolean_jdbc_type=BOOLEAN

# JWT
# Secret key should have at least 64 chars for HS512
jwt.secret=5b04a5e3d2f1a9c8b7e6d5c4f3a2b1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000

# Default admin bootstrap
app.init.admin.email=admin@tsis.com
app.init.admin.password=Admin123*
app.init.admin.nombre=Admin
app.init.admin.apellido=Principal

# Correo (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rodrigosoto433@gmail.com
spring.mail.password=ylwc oirw iamx pumt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Nombre visible en el "De:" del correo
parking.mail.from-name=Sistema de Parqueo UPB

server.port=8082


